// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.21.12
// source: internal/contracts/gcp.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GCPProviderConfig is the typed configuration for the iac.provider module
// provided by workflow-plugin-gcp. All fields correspond to the map keys
// accepted by the legacy Initialize(ctx, map[string]any) path.
type GCPProviderConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// project_id is the GCP project ID (required).
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// region is the GCP region (default: us-central1).
	Region string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	// zone is the GCP zone (default: us-central1-a).
	Zone string `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	// credentials_file is the path to a GCP service account JSON key file.
	// If empty, Application Default Credentials are used.
	CredentialsFile string `protobuf:"bytes,4,opt,name=credentials_file,json=credentialsFile,proto3" json:"credentials_file,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GCPProviderConfig) Reset() {
	*x = GCPProviderConfig{}
	mi := &file_internal_contracts_gcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCPProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCPProviderConfig) ProtoMessage() {}

func (x *GCPProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCPProviderConfig.ProtoReflect.Descriptor instead.
func (*GCPProviderConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gcp_proto_rawDescGZIP(), []int{0}
}

func (x *GCPProviderConfig) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GCPProviderConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GCPProviderConfig) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *GCPProviderConfig) GetCredentialsFile() string {
	if x != nil {
		return x.CredentialsFile
	}
	return ""
}

var File_internal_contracts_gcp_proto protoreflect.FileDescriptor

var file_internal_contracts_gcp_proto_rawDesc = string([]byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x73, 0x2f, 0x67, 0x63, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17,
	0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73,
	0x2e, 0x67, 0x63, 0x70, 0x2e, 0x76, 0x31, 0x22, 0x89, 0x01, 0x0a, 0x11, 0x47, 0x43, 0x50, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x46,
	0x69, 0x6c, 0x65, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x47, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x41, 0x6c, 0x6f, 0x6e, 0x65, 0x2f, 0x77, 0x6f,
	0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2d, 0x67, 0x63,
	0x70, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x73, 0x3b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_internal_contracts_gcp_proto_rawDescOnce sync.Once
	file_internal_contracts_gcp_proto_rawDescData []byte
)

func file_internal_contracts_gcp_proto_rawDescGZIP() []byte {
	file_internal_contracts_gcp_proto_rawDescOnce.Do(func() {
		file_internal_contracts_gcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_gcp_proto_rawDesc), len(file_internal_contracts_gcp_proto_rawDesc)))
	})
	return file_internal_contracts_gcp_proto_rawDescData
}

var file_internal_contracts_gcp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_contracts_gcp_proto_goTypes = []any{
	(*GCPProviderConfig)(nil), // 0: workflow.plugins.gcp.v1.GCPProviderConfig
}
var file_internal_contracts_gcp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_contracts_gcp_proto_init() }
func file_internal_contracts_gcp_proto_init() {
	if File_internal_contracts_gcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_gcp_proto_rawDesc), len(file_internal_contracts_gcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_gcp_proto_goTypes,
		DependencyIndexes: file_internal_contracts_gcp_proto_depIdxs,
		MessageInfos:      file_internal_contracts_gcp_proto_msgTypes,
	}.Build()
	File_internal_contracts_gcp_proto = out.File
	file_internal_contracts_gcp_proto_goTypes = nil
	file_internal_contracts_gcp_proto_depIdxs = nil
}
