// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/contracts/gcp_plan2.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GCPCredentialsBlock mirrors the YAML `credentials:` sub-block the
// plan-2 gcp modules accept. Consumed by gcpcreds.BuildGCPOptions (see
// internal/gcpcreds/gcpcreds.go).
type GCPCredentialsBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// project_id is the GCP project ID. Carried for downstream consumers
	// (quota-project wiring); BuildGCPOptions itself does NOT synthesize a
	// credential option from project_id alone.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// service_account_json is an inline GCP service-account JSON key.
	// Non-empty → option.WithCredentialsJSON. Empty → Application Default
	// Credentials.
	ServiceAccountJson string `protobuf:"bytes,2,opt,name=service_account_json,json=serviceAccountJson,proto3" json:"service_account_json,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GCPCredentialsBlock) Reset() {
	*x = GCPCredentialsBlock{}
	mi := &file_internal_contracts_gcp_plan2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCPCredentialsBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCPCredentialsBlock) ProtoMessage() {}

func (x *GCPCredentialsBlock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gcp_plan2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCPCredentialsBlock.ProtoReflect.Descriptor instead.
func (*GCPCredentialsBlock) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gcp_plan2_proto_rawDescGZIP(), []int{0}
}

func (x *GCPCredentialsBlock) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GCPCredentialsBlock) GetServiceAccountJson() string {
	if x != nil {
		return x.ServiceAccountJson
	}
	return ""
}

// GCPCredentialsConfig is the typed configuration for the gcp.credentials
// standalone module. The module registers the parsed credentials block in
// the process-local credref registry under the module's own name so
// sibling storage.gcs modules can reference it via `credentials_ref:`.
type GCPCredentialsConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// project_id — top-level back-compat alias for credentials.project_id.
	// Nested credentials.project_id wins when both are supplied.
	ProjectId     string               `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Credentials   *GCPCredentialsBlock `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GCPCredentialsConfig) Reset() {
	*x = GCPCredentialsConfig{}
	mi := &file_internal_contracts_gcp_plan2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCPCredentialsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCPCredentialsConfig) ProtoMessage() {}

func (x *GCPCredentialsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gcp_plan2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCPCredentialsConfig.ProtoReflect.Descriptor instead.
func (*GCPCredentialsConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gcp_plan2_proto_rawDescGZIP(), []int{1}
}

func (x *GCPCredentialsConfig) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GCPCredentialsConfig) GetCredentials() *GCPCredentialsBlock {
	if x != nil {
		return x.Credentials
	}
	return nil
}

// GCSStorageConfig is the typed configuration for the storage.gcs module.
// The module exposes List/Get/Put/Delete/Stat/MkdirAll operations against
// the named bucket. Credentials come from EITHER the inline
// `credentials:` block OR `credentials_ref:` (a sibling gcp.credentials
// module name) — inline wins when both are supplied; empty → Application
// Default Credentials.
type GCSStorageConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bucket is the GCS bucket name (REQUIRED).
	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// prefix is an optional object-key prefix applied to all operations.
	Prefix string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// credentials_ref names a gcp.credentials module to look up in the
	// process-local credref registry. Mutually exclusive with `credentials`;
	// inline credentials win when both are supplied.
	CredentialsRef string               `protobuf:"bytes,3,opt,name=credentials_ref,json=credentialsRef,proto3" json:"credentials_ref,omitempty"`
	Credentials    *GCPCredentialsBlock `protobuf:"bytes,4,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GCSStorageConfig) Reset() {
	*x = GCSStorageConfig{}
	mi := &file_internal_contracts_gcp_plan2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCSStorageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCSStorageConfig) ProtoMessage() {}

func (x *GCSStorageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_gcp_plan2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCSStorageConfig.ProtoReflect.Descriptor instead.
func (*GCSStorageConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_gcp_plan2_proto_rawDescGZIP(), []int{2}
}

func (x *GCSStorageConfig) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GCSStorageConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *GCSStorageConfig) GetCredentialsRef() string {
	if x != nil {
		return x.CredentialsRef
	}
	return ""
}

func (x *GCSStorageConfig) GetCredentials() *GCPCredentialsBlock {
	if x != nil {
		return x.Credentials
	}
	return nil
}

var File_internal_contracts_gcp_plan2_proto protoreflect.FileDescriptor

const file_internal_contracts_gcp_plan2_proto_rawDesc = "" +
	"\n" +
	"\"internal/contracts/gcp_plan2.proto\x12\x17workflow.plugins.gcp.v1\"f\n" +
	"\x13GCPCredentialsBlock\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x120\n" +
	"\x14service_account_json\x18\x02 \x01(\tR\x12serviceAccountJson\"\x85\x01\n" +
	"\x14GCPCredentialsConfig\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12N\n" +
	"\vcredentials\x18\x02 \x01(\v2,.workflow.plugins.gcp.v1.GCPCredentialsBlockR\vcredentials\"\xbb\x01\n" +
	"\x10GCSStorageConfig\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12'\n" +
	"\x0fcredentials_ref\x18\x03 \x01(\tR\x0ecredentialsRef\x12N\n" +
	"\vcredentials\x18\x04 \x01(\v2,.workflow.plugins.gcp.v1.GCPCredentialsBlockR\vcredentialsBIZGgithub.com/GoCodeAlone/workflow-plugin-gcp/internal/contracts;contractsb\x06proto3"

var (
	file_internal_contracts_gcp_plan2_proto_rawDescOnce sync.Once
	file_internal_contracts_gcp_plan2_proto_rawDescData []byte
)

func file_internal_contracts_gcp_plan2_proto_rawDescGZIP() []byte {
	file_internal_contracts_gcp_plan2_proto_rawDescOnce.Do(func() {
		file_internal_contracts_gcp_plan2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_gcp_plan2_proto_rawDesc), len(file_internal_contracts_gcp_plan2_proto_rawDesc)))
	})
	return file_internal_contracts_gcp_plan2_proto_rawDescData
}

var file_internal_contracts_gcp_plan2_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_contracts_gcp_plan2_proto_goTypes = []any{
	(*GCPCredentialsBlock)(nil),  // 0: workflow.plugins.gcp.v1.GCPCredentialsBlock
	(*GCPCredentialsConfig)(nil), // 1: workflow.plugins.gcp.v1.GCPCredentialsConfig
	(*GCSStorageConfig)(nil),     // 2: workflow.plugins.gcp.v1.GCSStorageConfig
}
var file_internal_contracts_gcp_plan2_proto_depIdxs = []int32{
	0, // 0: workflow.plugins.gcp.v1.GCPCredentialsConfig.credentials:type_name -> workflow.plugins.gcp.v1.GCPCredentialsBlock
	0, // 1: workflow.plugins.gcp.v1.GCSStorageConfig.credentials:type_name -> workflow.plugins.gcp.v1.GCPCredentialsBlock
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_contracts_gcp_plan2_proto_init() }
func file_internal_contracts_gcp_plan2_proto_init() {
	if File_internal_contracts_gcp_plan2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_gcp_plan2_proto_rawDesc), len(file_internal_contracts_gcp_plan2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_gcp_plan2_proto_goTypes,
		DependencyIndexes: file_internal_contracts_gcp_plan2_proto_depIdxs,
		MessageInfos:      file_internal_contracts_gcp_plan2_proto_msgTypes,
	}.Build()
	File_internal_contracts_gcp_plan2_proto = out.File
	file_internal_contracts_gcp_plan2_proto_goTypes = nil
	file_internal_contracts_gcp_plan2_proto_depIdxs = nil
}
